name: Build
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: master
      - name: Run pdflatex previous to bibtex on master
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Run bibtex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.aux
          compiler: bibtex
          args:
      - name: Run pdflatex on master
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload pdf to workflow
        uses: actions/upload-artifact@v2
        with:
          name: Compiled_file
          path: main.pdf
      - name: Push on master branch
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: 'master'
          commit-message: 'GitHub Action: Compile PDF'
          force-add: 'true'
          files: main.pdf
          name: Eneko Uruñuela
          email: e.urunuela@bcbl.eu
